url: https://bawee.github.io
baseurl:

# Site settings
title: Bryan's Website
email: b.wee@ed.ac.uk
description: "Bryan's website."


# Team names, titles and social links
people:
- name: Bryan Wee
  pic: 1
  position: Postdoctoral Research Fellow, University of Edinburgh
  social:
    - title: twitter
      url: www.twitter.com/bawee
    - title: linkedin
      url: www.linkedin.com/in/bawee
    - title: github
      url: http://github.com/bawee


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Ashworth Laboratories
  - line: King's Buildings, Edinburgh, United Kingdom
  
# Build settings
markdown: kramdown
permalink: pretty
