url: https://bawee.github.io
baseurl:

# Site settings
title: Bryan Wee
email:
description: "Bryan Wee"


# Team names, titles and social links
people:
- name:
  pic:
  position:
  social:

people:
- name: Bryan Wee
  pic: 1
  position: Core Scientist<br>The Roslin Institute<br>The University of Edinburgh
  social:
    - title: twitter
      url: http://www.twitter.com/bawee
    - title: linkedin
      url: http://www.linkedin.com/in/bawee
    - title: google
      url: https://scholar.google.co.uk/citations?user=Ua8vr-QAAAAJ&hl=en&oi=ao
    - title: github
      url: http://github.com/bawee
    - title: envelope
      url: mailto:b.wee@ed.ac.uk


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/bawee
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: linkedin
    url: http://www.linkedin.com/in/bawee
  - title: google
    url: https://scholar.google.co.uk/citations?user=Ua8vr-QAAAAJ&hl=en&oi=ao
  - title: github
    url: http://github.com/bawee
  - title: envelope
    url: mailto:b.wee@ed.ac.uk

# Postal address (add as many lines as necessary)
address:
  - line: The Roslin Institute
  - line: Edinburgh, Scotland, United Kingdom

# Build settings
markdown: kramdown
permalink: pretty
